Fix incorrect native message size reporting to Firefox
Nim's os.execCmd() will inherit the stdout/stderr from the calling
process (`native_main`), which means that running `mv/rm` with `-v` will
mess up "native_main"'s `stdout` and report incorrect native message
size to Firefox, resulting in error messages like the following in the
Tridactyl JavaScript world:

```
  ExtensionError: Native application tried to send a message of
  1702057263 bytes, which exceeds the limit of 1048576 bytes.
```

Interestingly, 1702057263 would be 0x6573552f in hex, and it would lead
to snippets like `/Use...` if converted to string (Python example
below).

```Python

  binascii.unhexlify(hex(1702057263).replace("0x", "")).decode(
      "utf-8"
  )[::-1]

  '/Use'
```

`/Use...` is something `mv/rm` commands tend to leave behind on
`stdout/stderr` depending on the source/destination files provided. For
example on Mac, user's may have invoked `saveas ~/Documents` which would
lead to `mv -v -f ~/Downloads/file.doc ~/Documents` being executed by
the native messenger.

The `-v` in `mv` would leave something like the following on `stdout`
that was breaking the native messenger and Firefox communication:

```
  /Users/name/Downloads/file.doc -> /Users/name/Documents/file.doc
```

These errors are fixed with this patch. Hopefully the details are
helpful to future similar debugging activities. Thank you.